name: socialnetwork_client
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  awesome_dio_interceptor: ^1.2.0
  path_provider: ^2.0.11
  hydrated_bloc: ^9.1.5
  injectable: ^1.5.3
  injectable_generator: ^1.5.4
  get_it: ^7.2.0
  dio: ^5.4.3+1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  json_serializable: ^6.5.1
  flutter:
    sdk: flutter 

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
